### ISSUE TITLE
Waiting for the meeting video recording to be available

### ISSUE THREAD

**Issue by brenjack** [designlogic/vend2000#1]
Hi. First let me say that your presentation and demo on TDD was really good! I didn't have visual studio installed on my computer so I couldn't really follow along at the time of the presentation. I was wondering if you knew if I believe his name is Tolci of the Roanoke .NET user group is going to upload the video recording. I needed to watch it again to follow along this time now that I have  Visual Studio installed.

**Comment by designlogic** [comment]
Terrific.  Thank you so much.  Yes, I believe that Tolga will be uploading the session to Youtube. I will keep an eye out for it and reach out to him if we don't see it pretty soon.  Thank you.

**Comment by brenjack** [comment]
Hi. I checked their youtube channel but I still don't see your presentation.

**Comment by designlogic** [comment]
Hi fmigsystems.   I'm so sorry,  I reached out to Tolga and haven't heard back yet.  I wish I had the recording to give you. It looks like they might take a few weeks before posting it on youtube.  You might also try posting a comment here https://www.meetup.com/roanoke-valley-net-user-group/events/287774393/ to see if they can upload the video sooner.

**Comment by brenjack** [comment]
Hi. So I left a message:
https://www.meetup.com/roanoke-valley-net-user-group/events/287774393/

I already forked vend2000 but I was wondering if you could post the complete solution that you did during the presentation on your github. I'll look at the solution and then go over it again. It was unfortunate that I did not have visual studio installed at the time. If you give another presentation, I'll be ready next time.

**Comment by designlogic** [comment]
Hi fmigsystems.  I have attached the solution I believe I used for the presentation.  I have also attached the "requirements" from the client.  I will definitely let you know if I do another presentation or put together a Udemy course. 
Thank you, Tyler 

[VendInternational.pdf](https://github.com/designlogic/vend2000/files/10047631/VendInternational.pdf)
[vend2000.zip](https://github.com/designlogic/vend2000/files/10047632/vend2000.zip)

**Comment by brenjack** [comment]
Is there a way to upgrade the entire project to .net 7. I'm on Visual Studo for mac version 17.4. Visual Studio keeps telling me to install .net 5 and I did and I cannot run the application.

**Comment by designlogic** [comment]
Sure. You should be able to change it in the project file (.csproj)

**Comment by brenjack** [comment]
Hi. So when I open the solutions vend2000, I get the following errors:
<img width="362" alt="Screenshot 2022-11-22 at 11 17 40 AM" src="https://user-images.githubusercontent.com/57248794/203208228-147f5a58-f021-48fb-8073-61d8c3f8b68c.png">
<img width="570" alt="Screenshot 2022-11-22 at 11 17 57 AM" src="https://user-images.githubusercontent.com/57248794/203208237-080b13d2-2cdb-41ce-aa69-5aaa08aed50e.png">

When I try to open the vend2000 without the solution, I get the following errors:
<img width="529" alt="Screenshot 2022-11-22 at 11 16 56 AM" src="https://user-images.githubusercontent.com/57248794/203208325-585f2853-3f6f-4dda-aef2-b42ee9c8f290.png">
<img width="1415" alt="Screenshot 2022-11-22 at 11 17 08 AM" src="https://user-images.githubusercontent.com/57248794/203208334-b7e2ae16-74b0-4a5e-9adb-57382e64b4ab.png">

I'm not sure if this is an issue only to Visual Studio on mac. I only have a mac computer and not a windows machine nor windows license.

**Comment by designlogic** [comment]
My bad.  This should be that Tests project. 
[Vend2000Tests.zip](https://github.com/designlogic/vend2000/files/10068941/Vend2000Tests.zip)

**Comment by designlogic** [comment]
Hello, it looks like they have uploaded the recording of the event.  Please let me know if you need anything.
https://youtu.be/hForXnc1OAc

**Comment by brenjack** [comment]
Thanks so much! I couldn't really replicate what you did in the meeting so I will look at the video again.
